---
-
  apt: "name=python-httplib2 update_cache=yes"
  name: "Install httplib2"
-
  action: "uri method=GET status_code=200 url=\"http://{{ rancher_server }}:{{ rancher_port }}/v1/projects\" return_content=yes"
  name: "Get the default project id"
  register: project_id
-
  action: "uri method=POST status_code=201 url=\"http://{{ rancher_server }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ project_id.json['data'][0]['id'] }}\" return_content=yes"
  name: "Return the registration token URL of Rancher server"
  register: rancher_token_url
-
  action: "uri method=GET url={{ rancher_token_url.json['links']['self'] }} return_content=yes"
  name: "Return the registration URL of Rancher server"
  register: rancher_token
-
  command: "docker ps -a"
  name: "Check if the rancher-agent is running"
  register: containers
-
  docker:
    command: "{{ rancher_token.json['registrationUrl'] }}"
    detach: true
    image: "rancher/agent:v{{ rancher_agent_version }}"
    privileged: true
    state: started
    volumes: "/var/run/docker.sock:/var/run/docker.sock"
  name: "Register the Host machine with the Rancher server"
  when: "{{ 'rancher-agent' not in containers.stdout }}"
-
  name: "Wait for the Rancher agent to start"
  wait_for: timeout=60
